import { radius, roundedRadius } from '../primitives/radius';

export const androidTokens = {
  platform: 'Android',
  viewport: {
    width: 360,
    height: 800,
  },
  size: {
    cellHeight: 52,
    fieldHeight: 44,
    searchHeight: 36,
    buttonExtraSmallHeight: 28,
    buttonSmallHeight: 36,
    buttonMediumHeight: 44,
    buttonLargeHeight: 52,
    panelHeaderHeight: 56,
    basePaddingHorizontal: 16,
    basePaddingVertical: 12,
    formItemPaddingVertical: 12,
  },
  typography: {
    family: {
      base: 'Roboto Flex',
      accent: 'VK Sans Display',
    },
    fontSize: {
      title1: 31,
      title2: 24,
      title3: 21.5,
      label1: 19,
      label2: 18,
      headline1: 17,
      body: 16.5,
      text: 16,
      paragraph: 15,
      footnote: 13.5,
      caption: 11.5,
    },
    letterSpacing: {
      title1: -0.5,
      title2: -0.09,
      title3: -0.15,
      label1: -0.14,
      label2: -0.19,
      headline1: -0.16,
      body: -0.21,
      text: -0.15,
      paragraph: -0.17,
      footnote: -0.16,
      caption: -0.12,
    },
    opticalSize: {
      title1: 31,
      title2: 28,
      title3: 28,
      label1: 26,
      label2: 26,
      headline1: 24,
      body: 24,
      text: 24,
      paragraph: 23,
      footnote: 23,
      caption: 22,
    },
    weight: {
      medium: 520,
      semiboldish: 580,
      semibold: 600,
      bold: 680,
    },
  },
  componentRadius: {
    base: 10,
    rounded: roundedRadius,
    paper: radius.sizeM,
    promo: radius.sizeXl,
    check: radius.size2xs,
    contextMenu: radius.size3xl,
  },
  componentSpacing: {
    cardGrid: 8,
    cardGridVertical: 8,
    contextMenuVertical: 14,
    horizontalCellSmall: 4,
    horizontalCellMedium: 6,
    snackbar: 8,
  },
  componentTypography: {
    largeButton: {
      fontSize: 16,
      lineHeight: 20,
      letterSpacing: 0,
    },
  },
} as const;
