import { radius, roundedRadius } from '../primitives/radius';

export const desktopTokens = {
  platform: 'Desktop',
  viewport: {
    width: 360,
    height: 800,
  },
  size: {
    cellHeight: 48,
    fieldHeight: 36,
    searchHeight: 32,
    buttonExtraSmallHeight: 24,
    buttonSmallHeight: 32,
    buttonMediumHeight: 36,
    buttonLargeHeight: 44,
    panelHeaderHeight: 48,
    basePaddingHorizontal: 16,
    basePaddingVertical: 12,
    formItemPaddingVertical: 12,
  },
  typography: {
    family: {
      base: 'SF Pro',
      accent: 'VK Sans Display',
    },
    fontSize: {
      title1: 31,
      title2: 24,
      title3: 21.5,
      label1: 19,
      label2: 18,
      headline1: 17,
      body: 16.5,
      text: 16,
      paragraph: 15,
      footnote: 13.5,
      caption: 11.5,
    },
    letterSpacing: {
      title1: 0,
      title2: 0,
      title3: 0,
      label1: 0,
      label2: 0,
      headline1: 0,
      body: 0,
      text: 0,
      paragraph: 0,
      footnote: 0,
      caption: 0,
    },
    opticalSize: {
      title1: 31,
      title2: 28,
      title3: 28,
      label1: 26,
      label2: 26,
      headline1: 24,
      body: 24,
      text: 24,
      paragraph: 23,
      footnote: 23,
      caption: 22,
    },
    weight: {
      medium: 520,
      semiboldish: 580,
      semibold: 600,
      bold: 700,
    },
  },
  componentRadius: {
    base: 10,
    rounded: roundedRadius,
    paper: radius.sizeM,
    promo: radius.sizeXl,
    check: radius.size2xs,
    contextMenu: radius.size3xl,
  },
  componentSpacing: {
    cardGrid: 8,
    cardGridVertical: 8,
    contextMenuVertical: 14,
    horizontalCellSmall: 8,
    horizontalCellMedium: 10,
    snackbar: 12,
  },
  componentTypography: {
    largeButton: {
      fontSize: 15,
      lineHeight: 20,
      letterSpacing: 0,
    },
  },
} as const;
