import { primitiveColors } from '../primitives/colors';

export const semanticColorsLight = {
  text: {
    primary: primitiveColors.darkGrey,
    primaryInvariably: primitiveColors.darkGrey,
    secondary: '#999999',
    tertiaryAlpha: 'rgba(59, 59, 59, 0.4)',
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.5)',
    contrastThemed: primitiveColors.white,
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.blue,
    positive: primitiveColors.green,
    negative: '#F65460',
    link: primitiveColors.blue,
    linkThemed: primitiveColors.blue,
    linkContrast: primitiveColors.white,
  },
  icon: {
    primary: primitiveColors.darkGrey,
    primaryInvariably: primitiveColors.darkGrey,
    medium: '#999999',
    secondary: '#B3B3B3',
    tertiary: '#D9D9D9',
    tertiaryAlpha: 'rgba(59, 59, 59, 0.4)',
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.blue,
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.5)',
    contrastThemed: primitiveColors.white,
    positive: primitiveColors.green,
    warning: primitiveColors.orange,
    negative: '#F65460',
  },
  background: {
    secondary: '#F2F2F2',
    tertiary: '#F7F7F7',
    inverse: '#262626',
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.2)',
    contrastInverse: primitiveColors.black,
    contrastThemed: primitiveColors.white,
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.blue,
    modal: primitiveColors.white,
    modalInverse: primitiveColors.black,
    positive: primitiveColors.green,
    positiveTint: '#E8F9E8',
    warning: '#FFF2D6',
    negative: '#F65460',
    negativeTint: '#FFE9E9',
    infoTint: '#DEEEFF',
  },
  stroke: {
    primary: primitiveColors.darkGrey,
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.blue,
    positive: primitiveColors.green,
    negative: '#F65460',
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.12)',
    imageBorderAlpha: 'rgba(51, 51, 51, 0.16)',
    fieldBorderAlpha: 'rgba(51, 51, 51, 0.04)',
  },
  separator: {
    primary: '#EBEBEB',
    primaryAlpha: 'rgba(0, 0, 0, 0.12)',
  },
  palette: {
    accentBlue: primitiveColors.blue,
    accentGray: '#A3ADB8',
    accentRed: '#FF5773',
    accentOrangeFire: '#F05C44',
    accentOrange: '#FF913D',
    accentOrangePeach: '#F9B54F',
    accentLime: '#AFF70D',
    accentGreen: '#42D347',
    accentMint: '#A3FD79',
    accentCyan: '#13FFD0',
    accentAzure: '#0077FF',
    accentPurple: '#735CE6',
    accentViolet: '#792EC0',
    accentRaspberryPink: '#FA7FBB',
    accentPink: '#E866FF',
    accentSecondary: '#3F8AE0',
  },
  other: {
    overlayPrimary: primitiveColors.darkGrey,
    overlaySecondary: 'rgba(59, 59, 59, 0.4)',
    avatarOverlayAlpha: 'rgba(59, 59, 59, 0.2)',
    skeletonFrom: '#F5F5F5',
    skeletonTo: '#EBEBEB',
    transparent: 'rgba(0, 0, 0, 0.0001)',
    transparentLight: 'rgba(255, 255, 255, 0.0001)',
  },
  states: {
    hover: {
      fieldBorderAlpha: 'rgba(51, 51, 51, 0.24)',
    },
    active: {
      fieldBorderAlpha: 'rgba(51, 51, 51, 0.36)',
    },
  },
} as const;
