import { primitiveColors } from '../primitives/colors';

export const semanticColorsDark = {
  text: {
    primary: primitiveColors.white,
    primaryInvariably: primitiveColors.darkGrey,
    secondary: '#666666',
    tertiaryAlpha: 'rgba(255, 255, 255, 0.5)',
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.5)',
    contrastThemed: primitiveColors.darkGrey,
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.white,
    positive: primitiveColors.green,
    negative: '#FD6571',
    link: primitiveColors.blue,
    linkThemed: primitiveColors.white,
    linkContrast: primitiveColors.white,
  },
  icon: {
    primary: primitiveColors.white,
    primaryInvariably: primitiveColors.darkGrey,
    medium: '#E6E6E6',
    secondary: '#666666',
    tertiary: '#4D4D4D',
    tertiaryAlpha: 'rgba(255, 255, 255, 0.5)',
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.white,
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.5)',
    contrastThemed: primitiveColors.black,
    positive: primitiveColors.green,
    warning: primitiveColors.orange,
    negative: '#FD6571',
  },
  background: {
    secondary: '#1E1E1C',
    tertiary: '#141414',
    inverse: primitiveColors.white,
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.2)',
    contrastInverse: primitiveColors.black,
    contrastThemed: '#1E1E1C',
    accent: primitiveColors.blue,
    accentThemed: primitiveColors.white,
    modal: primitiveColors.black,
    modalInverse: primitiveColors.white,
    positive: primitiveColors.green,
    positiveTint: '#273724',
    warning: '#483416',
    negative: '#FD6571',
    negativeTint: '#4B2727',
    infoTint: '#16334E',
  },
  stroke: {
    primary: primitiveColors.white,
    accent: '#529EF4',
    accentThemed: primitiveColors.white,
    positive: primitiveColors.green,
    negative: '#FD6571',
    contrast: primitiveColors.white,
    contrastSecondaryAlpha: 'rgba(255, 255, 255, 0.12)',
    imageBorderAlpha: 'rgba(255, 255, 255, 0.24)',
    fieldBorderAlpha: 'rgba(255, 255, 255, 0.06)',
  },
  separator: {
    primary: '#303030',
    primaryAlpha: 'rgba(255, 255, 255, 0.14)',
  },
  palette: {
    accentBlue: primitiveColors.blue,
    accentGray: '#A3ADB8',
    accentRed: '#FF5773',
    accentOrangeFire: '#F05C44',
    accentOrange: '#FF913D',
    accentOrangePeach: '#FFC062',
    accentLime: '#AFF70D',
    accentGreen: '#42D347',
    accentMint: '#A3FD79',
    accentCyan: '#13FFD0',
    accentAzure: '#0077FF',
    accentPurple: '#9985FF',
    accentViolet: '#A94FFF',
    accentRaspberryPink: '#FA7FBB',
    accentPink: '#E866FF',
    accentSecondary: '#3F8AE0',
  },
  other: {
    overlayPrimary: primitiveColors.darkGrey,
    overlaySecondary: 'rgba(59, 59, 59, 0.4)',
    avatarOverlayAlpha: 'rgba(59, 59, 59, 0.2)',
    skeletonFrom: '#1B1B1B',
    skeletonTo: '#262626',
    transparent: 'rgba(0, 0, 0, 0.0001)',
    transparentLight: 'rgba(255, 255, 255, 0.0001)',
  },
  states: {
    hover: {
      fieldBorderAlpha: 'rgba(255, 255, 255, 0.16)',
    },
    active: {
      fieldBorderAlpha: 'rgba(255, 255, 255, 0.2)',
    },
  },
} as const;
